### DISCUSSION TITLE
Running STAC Browser with URL at startup breaks on links to items

### DISCUSSION THREAD

**Discussion by alexgleith** [radiantearth/stac-browser#375] [General]
I'm running STAC Browser and using the entrypoint to configure a starting STAC API, like this:

```yaml
          env:
            - name: SB_catalogUrl
              value: "https://stac-api.staging.digitalearthpacific.org"
```

This works great, it loads up and clicking around works fine.

<img width="847" alt="image" src="https://github.com/radiantearth/stac-browser/assets/3445853/4ab1ee00-788d-44f8-b944-d745a28f585a">

But, if I follow the links to an item, like this `https://stac-browser.staging.digitalearthpacific.org/collections/dep_ls_wofs/items/dep_ls_wofs_TV_008_2022_mean` and copy and paste that into a browser, I get this error:

<img width="532" alt="image" src="https://github.com/radiantearth/stac-browser/assets/3445853/8c115e85-14bf-4e40-92f5-67c7ca3986b0">

The console logs this:

>Uncaught SyntaxError: Unexpected token '<' (at config.js:1:1)

It's trying to parse HTML as JSON, for some reason...

Any ideas what's going on?
